cc_library(
    name = "tracing_utils",
    hdrs = [
        "increment_with_saturation.hpp",
    ],
    tags = ["FUSA"],
    visibility = [
        "@score_baselibs//score/analysis/tracing:__subpackages__",
    ],
)
